site_name: DevOops Documentation
site_url: https://stewartmoreland.github.io/docs/
theme:
  name: material
  # logo: assets/logo-white.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
repo_name: stewartmoreland/docs
repo_url: https://github.com/stewartmoreland/docs

plugins:
  - social:
      cards: !ENV [CARDS, false]

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true

extra_css:
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
extra_javascript:
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
